import type {
  ItemCompanyInput,
  ItemEnrichmentInput,
  SourceItemUpsertInput,
  SourceUpsertInput,
  StockSnapshotInput,
  TickerCorrectionInput,
} from '../types';

const seededAt = '2026-04-25T09:00:00.000Z';
const laterAt = '2026-04-25T09:15:00.000Z';
const staleSnapshotCapturedAt = '2026-04-25T08:45:00.000Z';
const staleSnapshotStaleAfter = '2026-04-25T09:00:00.000Z';

export const sampleData = {
  sources: [
    {
      id: 'rss-finance-brief',
      type: 'rss',
      name: 'Finance Brief',
      enabled: true,
      config: {
        url: 'https://example.com/finance-brief.rss',
        refreshMinutes: 60,
      },
      createdAt: seededAt,
      updatedAt: seededAt,
    } satisfies SourceUpsertInput,
    {
      id: 'reddit-stocks-watch',
      type: 'reddit',
      name: 'Reddit Stocks Watch',
      enabled: true,
      config: {
        feedUrl: 'https://www.reddit.com/r/stocks/.rss',
        refreshMinutes: 30,
      },
      createdAt: seededAt,
      updatedAt: seededAt,
    } satisfies SourceUpsertInput,
  ],
  items: [
    {
      id: 'item-msft-complete',
      sourceId: 'rss-finance-brief',
      externalId: 'finance-brief-msft',
      canonicalUrl: 'https://example.com/articles/msft-azure-expansion',
      title: 'Microsoft expands Azure capacity for AI workloads',
      summary: 'Microsoft plans additional Azure capacity in several regions.',
      author: 'Casey Lee',
      publishedAt: seededAt,
      fetchedAt: seededAt,
      sourceMetadata: {
        feedTitle: 'Finance Brief',
        excerpt: 'Microsoft expands Azure capacity for AI workloads.',
      },
      readState: 'read',
      savedForResearch: true,
      enrichmentState: 'complete',
      createdAt: seededAt,
      updatedAt: laterAt,
    } satisfies SourceItemUpsertInput,
    {
      id: 'item-nvda-review',
      sourceId: 'reddit-stocks-watch',
      externalId: 'reddit-nvda-review',
      canonicalUrl: 'https://example.com/posts/nvidia-ai-server-supply',
      title: 'Supply chain notes around NVIDIA AI server demand',
      summary: 'Post discusses indirect evidence around NVIDIA server demand.',
      author: 'marketwatcher',
      publishedAt: seededAt,
      fetchedAt: laterAt,
      sourceMetadata: {
        subreddit: 'stocks',
        postType: 'link',
      },
      readState: 'unread',
      savedForResearch: false,
      enrichmentState: 'needs_review',
      createdAt: seededAt,
      updatedAt: laterAt,
    } satisfies SourceItemUpsertInput,
    {
      id: 'item-tsla-failed',
      sourceId: 'rss-finance-brief',
      externalId: 'finance-brief-tsla',
      canonicalUrl: 'https://example.com/articles/tsla-delivery-miss',
      title: 'Tesla deliveries miss some estimates',
      summary: 'A short report on vehicle deliveries and margin pressure.',
      author: 'Jordan Fox',
      publishedAt: laterAt,
      fetchedAt: laterAt,
      sourceMetadata: {
        feedTitle: 'Finance Brief',
        excerpt: 'Tesla deliveries miss some estimates.',
      },
      readState: 'unread',
      savedForResearch: false,
      enrichmentState: 'failed',
      createdAt: seededAt,
      updatedAt: laterAt,
    } satisfies SourceItemUpsertInput,
    {
      id: 'item-pending',
      sourceId: 'reddit-stocks-watch',
      externalId: 'reddit-pending',
      canonicalUrl: 'https://example.com/posts/pending-review',
      title: 'New item waiting on background enrichment',
      summary: 'This item is intentionally left pending for UI testing.',
      author: 'dailyreader',
      publishedAt: laterAt,
      fetchedAt: laterAt,
      sourceMetadata: {
        subreddit: 'stocks',
        postType: 'text',
      },
      readState: 'unread',
      savedForResearch: false,
      enrichmentState: 'pending',
      createdAt: seededAt,
      updatedAt: laterAt,
    } satisfies SourceItemUpsertInput,
  ],
  enrichments: [
    {
      id: 'enrichment-msft',
      sourceItemId: 'item-msft-complete',
      state: 'complete',
      summary:
        'Microsoft is relevant because the item directly discusses Azure expansion and AI infrastructure demand.',
      modelProvider: 'openai-compatible',
      modelName: 'local-model',
      promptVersion: 'v1',
      completedAt: laterAt,
      errorMessage: null,
      createdAt: seededAt,
      updatedAt: laterAt,
    } satisfies ItemEnrichmentInput,
    {
      id: 'enrichment-nvda',
      sourceItemId: 'item-nvda-review',
      state: 'needs_review',
      summary:
        'NVIDIA is a likely match, but the evidence is indirect and should be reviewed.',
      modelProvider: 'openai-compatible',
      modelName: 'local-model',
      promptVersion: 'v1',
      completedAt: laterAt,
      errorMessage: null,
      createdAt: seededAt,
      updatedAt: laterAt,
    } satisfies ItemEnrichmentInput,
    {
      id: 'enrichment-tsla',
      sourceItemId: 'item-tsla-failed',
      state: 'failed',
      summary: null,
      modelProvider: 'openai-compatible',
      modelName: 'local-model',
      promptVersion: 'v1',
      completedAt: null,
      errorMessage: 'OpenAI-compatible endpoint timed out',
      createdAt: seededAt,
      updatedAt: laterAt,
    } satisfies ItemEnrichmentInput,
  ],
  companies: [
    {
      itemId: 'item-msft-complete',
      companies: [
        {
          id: 'company-msft',
          sourceItemId: 'item-msft-complete',
          companyName: 'Microsoft',
          ticker: 'MSFT',
          exchange: 'NASDAQ',
          relationshipType: 'mentioned',
          relevanceExplanation:
            'The article directly names Microsoft in the context of Azure capacity expansion.',
          confidence: 0.98,
          matchStatus: 'validated',
          evidenceText: 'Microsoft expands Azure capacity for AI workloads',
          createdAt: seededAt,
          updatedAt: laterAt,
        } satisfies ItemCompanyInput,
      ],
    },
    {
      itemId: 'item-nvda-review',
      companies: [
        {
          id: 'company-nvda',
          sourceItemId: 'item-nvda-review',
          companyName: 'NVIDIA',
          ticker: 'NVDA',
          exchange: 'NASDAQ',
          relationshipType: 'mentioned',
          relevanceExplanation:
            'The evidence suggests NVIDIA is relevant, but the mention is indirect.',
          confidence: 0.63,
          matchStatus: 'needs_review',
          evidenceText: 'Supply chain notes around NVIDIA AI server demand',
          createdAt: seededAt,
          updatedAt: laterAt,
        } satisfies ItemCompanyInput,
      ],
    },
  ],
  snapshots: [
    {
      id: 'snapshot-msft-stale',
      ticker: 'MSFT',
      exchange: 'NASDAQ',
      companyName: 'Microsoft',
      price: 425.12,
      currency: 'USD',
      dailyChange: -1.4,
      dailyChangePercent: -0.33,
      marketCap: 3_200_000_000_000,
      sector: 'Technology',
      provider: 'yahoo-finance2',
      capturedAt: staleSnapshotCapturedAt,
      staleAfter: staleSnapshotStaleAfter,
      raw: {
        symbol: 'MSFT',
        source: 'seed',
      },
      createdAt: seededAt,
    } satisfies StockSnapshotInput,
  ],
  corrections: [
    {
      id: 'correction-nvidia',
      companyName: 'NVIDIA',
      correctTicker: 'NVDA',
      correctExchange: 'NASDAQ',
      notes: 'Normalize the canonical ticker for NVIDIA mentions.',
      enabled: true,
      createdAt: seededAt,
      updatedAt: laterAt,
    } satisfies TickerCorrectionInput,
  ],
};
